### ISSUE TITLE
Oaxaca: mismatch in number of federal electoral districts

### ISSUE THREAD

**Issue by siwhitehouse** [everypolitician/proto-commons-mexico#15]
According to the [Mexican National Election Institute ](http://cartografia.ife.org.mx/sige7/?distritacion=federal) there are ten electoral districts in Oaxaca.
However, the website for the Mexican Chamber of Deputies has a listing for [Carlos Sarabia Camacho](http://sitl.diputados.gob.mx/LXIII_leg/curricula.php?dipt=208) that give his electoral district as the 11th federal electoral district of Oaxaca.
I have created a [Wikidata Item for the 11th federal electoral district of Oaxaca](https://www.wikidata.org/wiki/Q55841367).
Logged so this can be checked and updated as appropriate.

**Comment by GeoWill** [comment]
I'm inclined to close this. So far we've just been concerned with keeping proto-commons-repos current, and pg 139 of  _Acuerdo_INE_CG59_2017_Aprobacion_300_Distritos_Electorales_Federales_15mar17.pdf_ contained in   http://cartografia.ife.org.mx/descargas/distritacion2017/acuerdos/INE_CG59_2017.zip makes it look like there are only 10 districts. There was some confusion about Oaxaca, but unless we have a source that is clearly post July 2018 elections I would assume that 10 districts is correct.

**Comment by GeoWill** [comment]
In conclusion we added a P576 for 31st August 2018 to https://www.wikidata.org/wiki/Q55841367.
